{% set name = "azure-uhttp-c" %}
{% set version = "2020-12-09" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/Azure/azure-uhttp-c/archive/{{ version.replace('.', '-') }}.tar.gz
    fn: {{ name }}-{{ version }}.tar.gz
    sha256: 6b4516d7c753470ff15ae3ebf1e985a8aa6e22d82e7d2f4f0d7f33e4c186de21
    patches:
      - install.patch

build:
  number: 0
  skip: true  # [not win64]
  run_exports:
    - {{ pin_subpackage(name, exact=True) }}

requirements:
  build:
    - vs2017_win-64          # [win64]
    - cmake
    - ninja
  host:
    - azure-c-shared-utility
  run:
    - azure-c-shared-utility

test:
  commands:
    - if not exist %PREFIX%\\Library\\bin\\uhttp.dll exit 1  # [win]

about:
  home: https://github.com/Azure/azure-uhttp-c
  license: MIT
  license_file: LICENSE
  summary: |
    The uhttp provides a platform independent http implementation via the Azure C SDKs.

extra:
  recipe-maintainers:
    - seanyen
